theme: jekyll-theme-minimal

exclude:
  - .gitignore
  - requirements.txt
  - README.md
  - prediction_history.json

# Jekyll site settings
baseurl: "/mlops_assignment1"
url: "https://jadamhub.github.io"

# Enable GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Set default empty layout
defaults:
  - scope:
      path: ""
    values:
      layout: default