title: Penguins of Madagascar - Species Classification
description: Daily penguin species predictions
theme: jekyll-theme-cayman
baseurl: "/MLOps_Assignment1"
url: "https://jadamhub.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor